name: Test rascript-audit

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  test:
    name: test2
    runs-on: ubuntu-latest
    container: ghcr.io/joshraphael/rascript-audit:a8796a396b6efc7feeca584c0ef7cbb4b2b5f5b2
    steps:
      - name: Test RAScript Audit
        run: |
          sh /app/entry.sh
