name: Test rascript-audit

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  test:
    name: test2
    runs-on: ubuntu-latest
    container: ghcr.io/joshraphael/rascript-audit:latest
    steps:
      - name: Test RAScript Audit
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
