name: Go

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "**" ]

permissions:
  contents: write
  pull-requests: write
jobs:
  test:
    name: test1
    runs-on: ubuntu-latest
    steps:
      - name: Test RAScript Audit
        uses: joshraphael/rascript-audit@a996f90360728047cdcd336feb784daa326f8494
        with:
          game-id: 4111
          rascript: rascripts/4111.rascript
          # report: true
          # severity: error
