name: Go

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "**" ]

permissions:
  contents: write
  pull-requests: write
jobs:
  test:
    name: test1
    runs-on: ubuntu-latest
    steps:
      - name: Test RAScript Audit
        uses: joshraphael/rascript-audit@30e8c675bade509b4b284d231bf3a383bdb6b254
        with:
          game-id: 4111
          rascript: 4111
          report: true
          severity: error
