name: Go

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "**" ]

permissions:
  contents: write
  pull-requests: write
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Test RAScript Audit
        uses: joshraphael/rascript-audit@649b48d5831184c979db9865ec0f2465d99d9493
        with:
          game-id: 4111
          rascript: test
