name: Go

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "**" ]

permissions:
  contents: write
  pull-requests: write
jobs:
  test:
    name: test1
    runs-on: ubuntu-latest
    steps:
      - name: Test RAScript Audit
        uses: joshraphael/rascript-audit@v0.0.2
        with:
          game-id: 4111
          rascript: rascripts/test file.rascript
          report: true
          severity: error
  test2:
    name: test2
    runs-on: ubuntu-latest
    steps:
      - name: Test RAScript Audit 2
        uses: joshraphael/rascript-audit@v0.0.2
        with:
          game-id: 18190
          rascript: rascripts/18190.rascript
          report: true
          severity: error
