name: Go

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "**" ]

permissions:
  contents: write
  pull-requests: write
jobs:
  test:
    name: test1
    runs-on: ubuntu-latest
    steps:
      - name: Test RAScript Audit
        uses: joshraphael/rascript-audit@b457c46d231a0eef8a3e3f75a64bb678cae8539b
        with:
          game-id: 4111
          rascript: rascripts/4111.rascript
          report: true
          severity: error
