name: Go

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "**" ]

permissions:
  contents: write
  pull-requests: write
jobs:
  test:
    name: test1
    runs-on: ubuntu-latest
    steps:
      - name: Test RAScript Audit
        uses: joshraphael/rascript-audit@4afc609b58fa5247dc3e5a392748b13d12a51eb6
        with:
          game-id: 4111
          rascript: rascripts/4111.rascript
          report: true
          severity: error
