name: Go

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "**" ]

permissions:
  contents: write
  pull-requests: write
jobs:
  test:
    name: test1
    runs-on: ubuntu-latest
    steps:
      - name: Test RAScript Audit
        uses: joshraphael/rascript-audit@10c7c81c48cce43ebe5f3014c7a32bfa29e94fb2
        with:
          game-id: 4111
          rascript: rascripts/4111.rascript
          report: true
          severity: error
