name: Go

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "**" ]

permissions:
  contents: write
  pull-requests: write
jobs:
  test:
    name: test1
    runs-on: ubuntu-latest
    steps:
      - name: Test RAScript Audit
        uses: joshraphael/rascript-audit@3faa1804675a11be3d140e543bac5afdfc7c6502
        with:
          game-id: 4111
          rascript: rascripts/4111.rascript
          report: true
          severity: error
