name: Go

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "**" ]

permissions:
  contents: write
  pull-requests: write
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Test RAScript Audit
        uses: joshraphael/rascript-audit@4e2355ec350161e9055e6b2146b671c5a4edf7e0
        with:
          game-id: 4111
          rascript: test
