name: Go

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "**" ]

permissions:
  contents: write
  pull-requests: write
jobs:
  test:
    name: test1
    runs-on: ubuntu-latest
    steps:
      - name: Test RAScript Audit
        uses: joshraphael/rascript-audit@e27bc94e12b599552a8753b9ee1f51f7a2bed212
        with:
          game-id: 4111
          rascript: rascripts/4111.rascript
          report: true
          severity: error
