name: Go

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "**" ]

permissions:
  contents: write
  pull-requests: write
jobs:
  test:
    name: test1
    runs-on: ubuntu-latest
    steps:
      - name: test
        shell: bash
        run: |
          echo "SECRET_GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}" >> "${GITHUB_OUTPUT}"
      - name: Test RAScript Audit
        uses: joshraphael/rascript-audit@11895cfe5a28a509753b6f9ae372d4b815679109
        with:
          game-id: 4111
          rascript: 4111
          report: true
          severity: error
