name: Go

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "**" ]

permissions:
  contents: write
  pull-requests: write
jobs:
  test:
    name: test1
    runs-on: ubuntu-latest
    steps:
      - name: Test RAScript Audit
        uses: joshraphael/rascript-audit@7c3b41078cf12b265e6b035fd738126ac13c2389
        with:
          game-id: 4111
          rascript: rascripts/4111.rascript
          report: true
          severity: error
