name: Go

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "**" ]

permissions:
  contents: write
  pull-requests: write
jobs:
  test:
    name: test1
    runs-on: ubuntu-latest
    steps:
      - name: Test RAScript Audit
        uses: joshraphael/rascript-audit@472b90d63e8035b3db0ffea95ce918fa881c9bfa
        with:
          game-id: 4111
          rascript: rascripts/4111.rascript
          report: true
          severity: error
